# Generated by Django 3.1 on 2020-08-21 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0003_auto_20200821_1154'),
        ('documentos', '0002_documento_pertence_funcionario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertence_funcionario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.funcionario'),
            preserve_default=False,
        ),
    ]
