# Generated by Django 3.1 on 2020-08-24 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='pertence_funcionario',
            new_name='pertence',
        ),
    ]
